"""Add level to user

Revision ID: 76f8df4153a3
Revises: fb3ae89499aa
Create Date: 2025-05-28 18:37:33.095872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f8df4153a3'
down_revision: Union[str, None] = 'fb3ae89499aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('achievements', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'achievements')
    op.drop_column('users', 'experience_points')
    # ### end Alembic commands ###
