"""Add is_generated to quiz_submissions

Revision ID: 95e4f69f0b6a
Revises: 9376e770f8f3
Create Date: 2025-05-26 12:33:39.736545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e4f69f0b6a'
down_revision: Union[str, None] = '9376e770f8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submissions', sa.Column('is_generated', sa.Boolean(), nullable=True))
    op.add_column('quiz_submissions', sa.Column('ai_questions', sa.JSON(), nullable=True))
    op.add_column('quiz_submissions', sa.Column('ai_answers', sa.JSON(), nullable=True))
    op.drop_column('quiz_submissions', 'submitted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submissions', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('quiz_submissions', 'ai_answers')
    op.drop_column('quiz_submissions', 'ai_questions')
    op.drop_column('quiz_submissions', 'is_generated')
    # ### end Alembic commands ###
