"""Add topic JSON

Revision ID: ba7066544b43
Revises: eea9eabcf1f4
Create Date: 2025-05-28 23:17:30.483908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7066544b43'
down_revision: Union[str, None] = 'eea9eabcf1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('topic_experience', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'topic_experience')
    # ### end Alembic commands ###
